//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionKey
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public System.DateTime ExpirationTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
